# Generated by Django 4.1.7 on 2023-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126, verbose_name='Примущество')),
                ('number', models.CharField(max_length=126, verbose_name='Цифра')),
                ('description', models.CharField(max_length=126, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=126, null=True, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=126, verbose_name='Текст')),
            ],
        ),
    ]
