# Generated by Django 4.1.7 on 2023-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Примущество'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Текст'),
        ),
    ]
